apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-cicd
spec:
  params:
    - name: gitrevision
      value: master
    - name: gitrepositoryurl
      value: https://github.com/lee-zhg/tutorial-tekton-argocd-code
    - name: contenttype
      value: $(header.content-type)
